### ISSUE TITLE
Respect `-Scp` and/or `-Sdeps`

### ISSUE THREAD

**Issue by terlar** [juxt/pack.alpha#103]
I have a project where $HOME is unwriteable, I would therefore like to be able to set `:mvn/local-repo`. Another option is to pre-calculate the classpath and pass it in via `-Scp`. This works for other aliases/commands, but seems to not work together with this tool.

Any ideas if this is possible or if there are any workarounds?

**Comment by SevereOverfl0w** [comment]
`-Scp` won't be supported.  Pack needs extended information that isn't present in the classpath.

`-Sdeps` wouldn't make sense in the current version of pack, as it's data-oriented now.  You can control the basis provided now. `:extra {:mvn/local-repo "..."}` should work in your call to `create-basis`.  That can then be passed to any of the pack functions.
