### ISSUE TITLE
juxt.pack.jib does not honor clojure.tools.build.api/*project-root* var

### ISSUE THREAD

**Issue by brianium** [juxt/pack.alpha#114]
Possibly related to #110 

Using tools.build with juxt.pack.jib creates issues related to the *project-root* used by toold.build:

Consider the following:

```clojure
(ns build
  (:require [clojure.tools.build.api :as b]
                 [juxt.pack.api :as pack]))

(b/with-project-root "path/to/my/project"
  (let [basis (b/create-basis {:project "deps.edn"
                               :aliases [:image]})]
    (pack/docker ...)))
```

deps.edn to illustrate the alias used

```clojure
{:aliases
 {:image {:paths     ["target/classes"]
          :main-opts ["-m" "regale.story-server.main"]}}}
```

This pulls classpath roots from the basis, so the above scenario results in a root that is still "target/classes", when it ought to be "path/to/my/project/target/classes".

This creates a problem with the `add-paths-entry` function used by the `make-builtin-layers` function. It causes the `(when (Files/exist))` check to fail.

I am able to fix the issue by resolving the root with `(clojure.tools.build.api/resolve-path root)`.  So `add-paths-entry` becomes:

```clojure
(defn- add-paths-entry
  [builder root]
  (let [root (.getPath (clojure.tools.build.api/resolve-path root))
        path (Paths/get root string-array)]
    (when (Files/exists path (into-array LinkOption []))
      (let [container-path (AbsoluteUnixPath/get (str target-dir
                                                      "/"
                                                      (unique-base-path path)))]
        {:builder
         (.addEntryRecursive builder
                             path
                             container-path
                             FileEntriesLayer/DEFAULT_FILE_PERMISSIONS_PROVIDER
                             timestamp-provider)
         :container-path container-path}))))
```

This handles the problem elegantly, but it introduces the dependency on tools.build.  I am more than willing to submit a PR, but unsure if the new dependency is welcome. Perhaps `:project-root` could be a new option supported by the  juxt.pack.jib/jib function for such cases?

Thanks again for this incredibly useful tool 🙇🏻

**Comment by SevereOverfl0w** [comment]
I'd prefer not to depend on tools.build at all, as there's no reason one needs to use that particular library.  It may fall out of fashion in years to come as some other library rises to replace it (who knows!).

tools.deps.alpha itself supports a `with-dir`, which is being [used by tools.build](https://github.com/clojure/tools.build/blob/654dc747d03caaae3592913a63596418d2fc8060/src/main/clojure/clojure/tools/build/tasks/create_basis.clj#L29) under the hood.

I think we should use `tools.deps.alpha.util.dir/canonicalize` and have users call `with-dir` themselves.  I'm happy to couple pack.alpha (further) with tools.deps.alpha in this way.

**Comment by SevereOverfl0w** [comment]
As an aside, tools.deps.build/create-basis might include the user deps.edn, I think? https://github.com/juxt/pack.alpha/blob/c1b7b904f7a5ba562553f4a1ad1e7167babf5b64/src/juxt/pack/cli/api.clj#L6-L9 has the code to strip the user deps.edn, or you could use that function itself maybe.

**Comment by SevereOverfl0w** [comment]
Wrapping calls to pack like:

```clojure
(tools.deps.alpha.util.dir/with-dir b/*project-root*
  (pack/...))
```

Should now work.  If this works well for you, I'd appreciate a quick doc update under https://github.com/juxt/pack.alpha#with-tools-build

**Comment by brianium** [comment]
@SevereOverfl0w thank you for this. This approach works well 🙇🏻 

I will submit a PR to the README. It looks like `tools.deps` is no longer in alpha, and the call to `with-dir` should wrap `b/*project-root*` with a call to `clojure.java.io/file`.

Thank you so much. Documentation PR incoming.
