### ISSUE TITLE
main-opts and jvm-opts are being extracted from basis incorrectly

### ISSUE THREAD

**Issue by puredanger** [juxt/pack.alpha#118]
In doing some work on the basis recently, I discovered that due to some sloppy coding on my part, the basis contained more data than it should have in the `:resolve-args` and `:classpath-args` keys.

In particular these two code locations are pulling either `:jvm-opts` or `:main-opts` from the `:classpath-args` map. Neither of these are classpath args and were never expected to be data that should be there:

* https://github.com/juxt/pack.alpha/blob/master/src/juxt/pack/jib.clj#L222
* https://github.com/juxt/pack.alpha/blob/master/src/juxt/pack/jib.clj#L229
* https://github.com/juxt/pack.alpha/blob/master/src/juxt/pack/one_jar.clj#L129

So, you should not be doing that. However, I do think it is reasonable to want those merged jvm-opts and main-opts and the basis now contains an official place to get that info in a basis key `:argmap`.

To fix, update to at least tools.deps 0.17.1297, and replace `:classpath-args` with `:argmap`. The `:classpath-args` are deprecated and will be removed once the small number of users have updated.

**Comment by SevereOverfl0w** [comment]
Perfect, thank you.  I mentioned in slack at the time that there was no official source for this information so I was going to be cheeky.  I'll get this sorted soon.
