### ISSUE TITLE
AOT support for skinny jar?

### ISSUE THREAD

**Issue by zerg000000** [juxt/pack.alpha#19]
the current approach will only include the source files in the jar, shall we support AOT compile before making the jar?

**Comment by SevereOverfl0w** [comment]
Skinny jar supports a `-e` flag which can be used to point at a directory with AOT compiled classes in. Edge has an example of this in https://github.com/juxt/edge/blob/d1b76fcff604ea033bc76547a26400a63fe24fa2/bin/uberjar
