### ISSUE TITLE
Java 9/10 `javax.xml.bind.DatatypeConverter` issue

### ISSUE THREAD

**Issue by rgm** [juxt/pack.alpha#25]
It seems [this function](https://github.com/juxt/pack.alpha/blob/master/src/mach/pack/alpha/impl/elodin.clj#L12) in `elodin.clj` is causing my attempts to package with Java 10 to fail. (I'm trying out the onejar packager).

```clj
(defn- signature
  [algorithm]
  (javax.xml.bind.DatatypeConverter/printHexBinary (.digest algorithm)))
```

This seems to be a similar issue to https://github.com/ztellman/aleph/issues/383 (and I think I've seen similar ones sprinkled about other projects), where `javax.xml.bind.DatatypeConverter` isn't getting included by default any more in Java 9+.

I've managed to paper it over with adding a `:jvm-opts` to my pack alias, like so:

```clj
  :pack
  {:extra-deps
   {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git"
                     :sha "ddbbdbd4001c75647deddaad0f8bb7dc954fcb6f"}}
   :jvm-opts ["--add-modules" "java.xml.bind"]
;; ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   :main-opts ["-m"]}}
```

I'd be happy to help out with a PR, but I'd like to ask for some direction since I don't know the best way to cope with this: adjust the `deps.edn` injector? Rely on a different signature generator?

**Comment by SevereOverfl0w** [comment]
I think that code can now be deleted, I have a commit at `351c55d51122f778f29ab334c5162ecbbded582e` which means Elodin no longer uses SHAs to determine names, it uses coord information.

**Comment by SevereOverfl0w** [comment]
Can you confirm whether latest master (`0878b52b7718e4b348a500dce0b3edc5b555a4f1`) solves this for you?

**Comment by rgm** [comment]
It did, 👍. Thanks so much.

**Comment by SevereOverfl0w** [comment]
Excellent. Pure coincidence of timing that I fixed this :grin:
