### ISSUE TITLE
Lambda example clobbers deps.edn.

### ISSUE THREAD

**Issue by eigenhombre** [juxt/pack.alpha#26]
Running the example in the README verbatim: `clj -A:pack mach.pack.alpha.aws-lambda deps.edn lambda.zip build_dir`

... clobbers the current `deps.edn` and replaces it with a binary file.

However,
`clj -A:pack mach.pack.alpha.aws-lambda lambda.zip` seems to produce a Zip file with Clojure source and jar files.

**Comment by SevereOverfl0w** [comment]
@eigenhombre are you running the commit on master? I think I changed lambda's call signature, and forgot to update the README.

I'd really love to automate this somehow. I think `--help` should tell you what I've changed.

I apologize for any trouble this has caused.

**Comment by eigenhombre** [comment]
Not a problem @SevereOverfl0w ... I just followed the example in the README:
`clojure -Sdeps '{:deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git" :sha "dccf2134bcf03726a9465d2b9997c42e5cd91bff"}}}' -m mach.pack.alpha.inject 'ddbbdbd4001c75647deddaad0f8bb7dc954fcb6f'`

... which worked great, then:

`clj -A:pack mach.pack.alpha.aws-lambda deps.edn lambda.zip build_dir` (clobbered `deps.edn`, as described in this issue).

If I strip off `deps.edn` and `build_dir`, it does produce a zip file.  But I am using https://github.com/uswitch/lambada to create the Clojure function for the lambda, and that does not work if I upload the resulting zip file to AWS (upon lambda invocation, it throws some sort of exception which doesn't even make it into CloudWatch).

A minimum viable Clojure snippet in addition to the `clj -A:pack` command, to produce a working lambda, would be a helpful addition to your docs. Will keep trying to get things to work in the mean time.  Thanks for making `pack.alpha`!

**Comment by SevereOverfl0w** [comment]
I can fix the example in the README, certainly :smile: 

Lambada uses `gen-class`, which I don't think works unless you perform aot compilation. The process would be to:

Add an alias named `:aot` to your deps.edn like so:

```
{:extra-paths ["classes"]
 :main-opts ["-e" "(compile,'entrypoint.core)"]}
```

```
clojure -A:aot
clojure -A:pack mach.pack.alpha.aws-lambda -e classes lambda.zip
```

Should then work for you.

**Comment by eigenhombre** [comment]
Verified that the new README step doesn't clobber my `deps.edn`. Thanks! Trying out the lambda example now....

**Comment by eigenhombre** [comment]
@SevereOverfl0w Your lambda example from this repo's README, plus the Lambada skeleton, worked for me. Thanks!!!
