### ISSUE TITLE
Class not found errors using Capsule uberjars on Hadoop

### ISSUE THREAD

**Issue by jarohen** [juxt/pack.alpha#33]
Leaving this here in the vague hope it saves someone else an afternoon - apologies if this is well-known :)

I was using the Capsule-based uberjar to submit an uberjar to Hadoop/EMR - was getting errors that it couldn't find some of the standard provided Hadoop classes. My current theory is that this was caused by Capsule overriding the classloader - works fine when it's the _only_ JAR on the classpath, but then not so well when Hadoop tries to augment the classpath with it's own JARs? 

In any event, I swapped to using `depstar` (well, Sean Corfield's fork), now works fine :)

HTH!

James

**Comment by SevereOverfl0w** [comment]
This would be correct. I briefly looked into hadoop, I believe that the lambda-produced items would work for it, with some tweaking of paths. That would be the approach to take if you wanted to embrace the pack philosophy of non flat classpaths.

**Comment by SevereOverfl0w** [comment]
Actually, I think it would be the skinny mode for hadoop, but I'm not doing hadoop, so I can't comment.
