### ISSUE TITLE
:extra-paths in aliases aren't packed

### ISSUE THREAD

**Issue by RickMoynihan** [juxt/pack.alpha#36]
I'm not sure if this only effects the capsule mechanism, but it seems that `:extra-paths` in aliases supplied at package time aren't included in the resultant capsule, though paths supplied via `--extra-paths` are.

I've attached a tar.gz file of a simple project proving the issue.

[packalphatest.tar.gz](https://github.com/juxt/pack.alpha/files/3229091/packalphatest.tar.gz)

To run:

1. `tar zxvf packalphatest.tar.gz`
2. `cd packalphatest`
3. `clj -A:foo:makecapsule` to try and include the `:foo` alias which defines `:extra-paths ["foo"]`
4. `jar xvf foo.jar` extract the build jar
5. `jar tvf project.jar` to show the contents of the project.jar, note that it does not contain the file `foo-file` from the `foo/` directory.

**Comment by SevereOverfl0w** [comment]
I think there's been a slight misunderstanding of how this works.  Pack doesn't look at the aliases it was started with, it instead needs a separate alias argument.

I changed `:makecapsule` to:

```
["-m" "mach.pack.alpha.capsule" "foo.jar"
 "-A:foo"
 "--application-id" "foo"
 ]
```

and it included foo-file in the jar.
