### ISSUE TITLE
capsule jars fail to unpack classpath properly for jar dependencies with /'s in their version string

### ISSUE THREAD

**Issue by RickMoynihan** [juxt/pack.alpha#38]
This might be uncommon but if a dependencies maven version string contains a `/` then it is treated like a nested folder within the uberjar capsule, and that jar fails to be included properly in the classpath.

This came up because our CI puts the `$GIT_BRANCH` name into the version string for PRs it builds, and we often namespace our branches with a `/` e.g. `rick/feature-1` as github have UI foldering conventions for.

**Comment by SevereOverfl0w** [comment]
I didn't even know this was possible in maven version strings! Can you try this commit and let me know? ^

**Comment by RickMoynihan** [comment]
Looks good thanks.  Sorry for the late reply.
