### ISSUE TITLE
Arguments aren't parsed exactly as they are by clojure.ps1

### ISSUE THREAD

**Issue by johnjelinek** [juxt/pack.alpha#40]
Build process is:
```
> clj -A:aot
rotate-credentials.core

> clj -A:pack -C:aot mach.pack.alpha.aws-lambda lambda.zip
```
(side-note: On Windows 10 Pro, if I do `-C:aot` right before `lambda.zip`, it makes a file called `aot`)

Anyway, the problem is that the classes for my project don't make it into the uberjar, only the dependencies (only `.clj` files exist in the non-lib directory):
```
├───lambda.zip
│   ├───data_access
│   ├───lib
│   └───rotate_credentials
```

When I run my lambda, I get this error:
```
Class not found: rotate-credentials.core: java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: rotate-credentials.core
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
```

This works fine if I build on linux. My java version is:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment Corretto-8.212.04.1 (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM Corretto-8.212.04.1 (build 25.212-b04, mixed mode)
```

**Comment by johnjelinek** [comment]
This command got me some class files in the zip, but I still can't refer to my handler (`rotate-credentials.core`):
```
clj -A:pack -C:aot mach.pack.alpha.aws-lambda --extra-path classes lambda.zip
```

**Comment by johnjelinek** [comment]
ah, I needed to `s/-/_/` in the handler name (`rotate_credentials.core`). So, why do I have to specify `--extra-paths` on windows, but not on linux?

**Comment by SevereOverfl0w** [comment]
What does your :aot alias look like?

**Comment by SevereOverfl0w** [comment]
I realize that you're probably using the one from the README. The command you're using (your particular placement of `-C:aot`) means that pack isn't using the aot alias.

I just tested, and the `clojure -A:pack mach.pack.alpha.aws-lambda -C:aot lambda.zip` invocation works for me on Linux.  My 2 ideas are:

1. You're using an old version of pack, what sha is in your deps.edn?
2. If this is only broken on Windows (i.e. it works for you on a *nix) then maybe there's something wrong with the argument parsing, but I'm quite skeptical of that, I'm using tools.cli

Given your `aot.zip`, I highly suspect that you're using an old version of pack which used positional arguments.

**Comment by johnjelinek** [comment]
the command you listed works fine on linux, but not on Windows. Here's my `deps.edn`:
```clojure
{:deps {org.clojure/clojure {:mvn/version "1.10.0"}
        org.clojure/data.json {:mvn/version "0.2.6"}
        com.amazonaws/aws-lambda-java-core {:mvn/version "1.2.0"}
        com.amazonaws/aws-lambda-java-events {:mvn/version "2.2.6"}
        http-kit {:mvn/version "2.3.0"}
        amazonica {:mvn/version "0.3.143"
                   :exclusions [com.amazonaws/aws-java-sdk
                                com.amazonaws/amazon-kinesis-client]}
        com.amazonaws/aws-java-sdk-core {:mvn/version "1.11.573"}
        com.amazonaws/aws-java-sdk-secretsmanager {:mvn/version "1.11.573"}
        com.taoensso/timbre {:mvn/version "4.10.0"}}
 :aliases {:pack {:extra-deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git"
                                                :sha "81b9e47d992b17aa3e3af1a47aed1f0287ebe9b8"}}
                  :main-opts ["-m"]}
           :aot {:extra-paths ["classes"]
                 :main-opts ["-e" "(compile,'rotate-credentials.core)"]}}}
```

When I end the command with `-C:aot lambda.zip` on windows, I don't get a file called `aot.zip`, just `aot` and it happens to be a compressed file (prolly mime type of zip), but no extension. This command works on windows: `clj -A:pack -C:aot mach.pack.alpha.aws-lambda --extra-path classes lambda.zip`

**Comment by SevereOverfl0w** [comment]
As a clearer example, I think that `clj -A:pack mach.pack.alpha.aws-lambda --extra-path classes lambda.zip` would work also on windows.

So, the question becomes, why is argument parsing broken on Windows? Are you using the WSL/GitBash or are you using the powershell version?

I've pushed up a sha which has tracing enabled for the AWS Lambda args, can you rerun your command on Windows with sha `417fc0ff0bc620a0dfaf5ce907436d5987e2fb59`? I do not have access to a Windows machine.

You should see a line like this when you've run it:

```
[trace] Arguments are:  ("-C:aot" "lambda.zip")
```

Hopefully this will help us track down what's different!

**Comment by johnjelinek** [comment]
Here's my output after using that sha:
```
> clj -A:pack -C:aot mach.pack.alpha.aws-lambda lambda.zip
[trace] Arguments are:  ("lambda.zip")
```
Here's with your recommended command:
```
> clj -A:pack mach.pack.alpha.aws-lambda --extra-path classes lambda.zip
[trace] Arguments are:  ("--extra-path" "classes" "lambda.zip")
```

**Comment by SevereOverfl0w** [comment]
Please try `clj -A:pack mach.pack.alpha.aws-lambda -C:aot lambda.zip`

**Comment by johnjelinek** [comment]
```
> clj -A:pack mach.pack.alpha.aws-lambda -C:aot lambda.zip
[trace] Arguments are:  ("-C:" "aot" "lambda.zip")
```

**Comment by SevereOverfl0w** [comment]
Okay, this explains it. Windows must split on : as a separator. As  a workaround `-C :aot lambda.zip ` should work, but I'd like to figure out how to make this work on windows, if it is possible at all.

**Comment by johnjelinek** [comment]
that worked:
```
> clj -A:pack mach.pack.alpha.aws-lambda -C :aot lambda.zip
[trace] Arguments are:  ("-C" ":aot" "lambda.zip")
```

**Comment by johnjelinek** [comment]
Moving the `-C` earlier still doesn't work:
```
> clj -A:pack -C :aot mach.pack.alpha.aws-lambda lambda.zip
[trace] Arguments are:  ("lambda.zip")
```

**Comment by SevereOverfl0w** [comment]
Earlier will never work.

Just to check, are you using the powershell version of clj?

**Comment by SevereOverfl0w** [comment]
Just noticed that `-C :aot` worked, that's great news, exactly what I'd expect.  I've asked in #clj-on-windows in clojurians slack about the argument splitting.  I'll report back when I get an answer.

**Comment by johnjelinek** [comment]
ya, I'm using the Powershell version of clj -- that's the only version of clj I see mentioned for windows on clojure.org

**Comment by SevereOverfl0w** [comment]
On the slack, I've gotten to the bottom of the difference.

Part of the clojure powershell code is designed in such a way that it takes `-R: foo` and converts it to the equivalent of `-R:foo` in Linux.  Pack doesn't have this kind of code.

As a workaround you can either manually split using `-R :foo`, or you can quote like `'-R:foo'`.

I'm not yet sure how I want to fix this.  Having a function called on `args` everywhere seems a little annoying but straightforward (this might not be true - e.g. for capsule's main opts, we don't want to process those!).  I will accept a PR that makes that change, but before I make the change myself I'm going to think about whether there's a better way to implement it.
