### ISSUE TITLE
Support labels in Jib builds

### ISSUE THREAD

**Issue by ivarref** [juxt/pack.alpha#45]
Hi,

and thanks for a great tool!

Would it be possible to add support for build labels in the Jib/Docker task?

Normally my docker build command would look something like:
`docker build ... --label version=$CI_PIPELINE_ID --label commit=${CI_COMMIT_SHORT_SHA} ... --tag ... .`

These properties are helpful for debugging when using `docker inspect ...`

I see that JibContainerBuilder has a [addLabel](https://static.javadoc.io/com.google.cloud.tools/jib-core/0.10.0/com/google/cloud/tools/jib/api/JibContainerBuilder.html#addLabel-java.lang.String-java.lang.String-) method, so I think it should be straight forward to add, though I have not read `pack.alpha`'s code (yet).

CC @viesti @SevereOverfl0w
Tagging you because you were active in the initial Docker/Jib-issue.

Thanks and kind regards!

**Comment by viesti** [comment]
Thanks for mentioning labels, seems like a useful thing that I haven't run into yet :)

I think a `--label` cli option would be great fit for this. Seems like the namespaces in pack.alpha are quite independent which makes it easy to add new tools while keeping shared code in separate namespaces. I don't know if a `pack.edn` config file would be in the horizon, but currently I'm thinking that cli options per tool are quite fitting.

I've been meaning to add a `--user` to be able to specify a user that the process is run with. `--label` would not clash with that option :)

If you want to take a stab at [jib.clj](https://github.com/juxt/pack.alpha/blob/master/src/mach/pack/alpha/jib.clj) I can help in reviewing, in case I don't get to adding `--label` myself :)

**Comment by ivarref** [comment]
Thanks a lot @viesti and @SevereOverfl0w ! Works nicely.
