### ISSUE TITLE
Faster startup for Docker images?

### ISSUE THREAD

**Issue by ivarref** [juxt/pack.alpha#61]
Hi

And thanks again for a great project!

I've noticed that startup time for my application increases as more dependencies is added.
The startup time is now about 20~25 seconds I believe.

Would it be possible to AOT compile dependencies and the project itself to reduce startup time?
Is this something that could be done?

Thanks and kind regards.

**Comment by SevereOverfl0w** [comment]
You can do this by calling clojure.core/compile and then passing the output directory via -e to pack

**Comment by ivarref** [comment]
Thanks.

My though/idea was that the jib task should do this automatically itself though. Each library/dependency should be AOT compiled as needed. This could be cached easily. The project itself should then be AOT compiled. What do you think? Does that make sense? I think it could greatly reduce startup time of applications.

I could look into a pull request for this.

Thanks again.

**Comment by ivarref** [comment]
Hi, and thanks for replying so quickly.

I did not realise caching AOT was difficult.

However, I've stumbled upon a different but related problem:

```bash
~/code/github/pack.alpha/sample$ ./pack.sh
...
+ docker run -it demo:pack
JVM booted in 10027 ms

~/code/github/pack.alpha/sample$ ./docker.sh
...
+ docker run -it demo:docker
JVM booted in 2774 ms
```

This is using the folder available at:

https://github.com/ivarref/pack.alpha/tree/master/sample

It seems that using jib/pack adds about ~7 seconds to the startup time of an AOT application compared to an AOT application built by docker.

What could be wrong here? I'm guessing that somehow clojure files are getting compiled even though they are already AOT-ed, but I'm not sure.

Regards.

**Comment by SevereOverfl0w** [comment]
To verify, you could add a println into a macro

**Comment by ivarref** [comment]
Thanks @SevereOverfl0w 

I did just that, and from what I can tell a regular docker build is fine, while a jib task does not do AOT correctly or this is not detected properly by the JVM/Clojure. I've updated the repo above to reproduce this. The docker version does not print `making macro!`, but the pack/jib does print this when running.

Any ideas?

PS. I noticed that for the docker version that setting the classpath to `classes:lib/lib/*` effectively disabled AOT when `target/lib` was copied to `/app/target/lib`. Strange behaviour.

I also tried setting the timestamp in the jib task like this (without effect):

```clojure
(.addLayer (-> (LayerConfiguration/builder)
                       (.setName "target/classes")
                       (.addEntryRecursive (Paths/get "target/classes" string-array)
                                           (AbsoluteUnixPath/get "/app/classes")
                                           LayerConfiguration/DEFAULT_FILE_PERMISSIONS_PROVIDER
                                           (reify BiFunction
                                             (apply [this source-path destination-path]
                                               (Instant/ofEpochSecond
                                                 (.toEpochSecond (ZonedDateTime/parse
                                                                   "2011-12-03T10:15:30+01:00[Europe/Paris]"
                                                                   DateTimeFormatter/ISO_ZONED_DATE_TIME))))))
                       (.build)))
```

**Comment by SevereOverfl0w** [comment]
I'll have a poke. My suspicion is that the classes folder isn't being used, as that's the most obvious reason.

Could be tested with an io/resource call to something only in that folder.

**Comment by ivarref** [comment]
Thanks @SevereOverfl0w 

I finally figured it out why this happened.

It seems that Clojure will prefer clj files found inside jars if they have a newer lastModified date than the corresponding class file. That makes sense. GoogleContainerTools/jib by default makes lastModified to 1000 when adding files. Thus clj files inside jars (with newer lastModified) would always be preferred over class files (with lastModified 1000).

The regular docker build does not do this, and hence here timestamps were correct, but the build not strictly reproducible.

With the changes in https://github.com/ivarref/pack.alpha/commit/bf90dd1daafa81466281b50508cda48b24c6f0b1 lastModified is set so that class files are preferred over JAR clj files.

I can look into providing a patch for this at a later time if that is of interest.

Thanks and kind regards.

**Comment by SevereOverfl0w** [comment]
That patch would be welcome. Although I think I'd prefer to retain the input modified dates unless there's a reason jib changes them?

**Comment by ivarref** [comment]
The reason jib changes them is to have 100% reproducible builds. The jib/FAQ explains it well: 

> Reproducible means that given the same inputs, a build should produce the same outputs. Container images are uniquely identified by a digest (or a hash) of the image contents and image metadata. Tools and infrastructure such [as] the Docker daemon, Docker Hub, registries, Kubernetes, etc) treat images with different digests as being different.

https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#why-is-my-image-created-48-years-ago

I think setting the timestamp of .class files to the highest possible value, and leaving the rest as epoch 1, is a decent way to support both Clojure AOT compilation and reproducible builds.

In alignment with this, it would be good if we could also specify setting the creation time of the image explicitly, to ensure totally reproducible builds. I was the one who wanted it to be set to `(Instant/now)`, sorry about that!

In the sample folder on `ivarref/pack.alpha`, adding `--no-cache` to the docker build command, makes the build unreproducible. You will get different sha256 sums (`docker inspect '--format={{index .Id}}' demo:docker`) after each build. We can do this better in pack.alpha.

**Comment by SevereOverfl0w** [comment]
This all makes sense to me :+1:

**Comment by ivarref** [comment]
Hi,

I added a pull request for this. Do you have possibility to have a look at it?

I still think that AOT-compilation should be an option, preferrably the default mode. This will decrease startup time, and it can also catch compile errors before they reach production.

Thanks!

**Comment by SevereOverfl0w** [comment]
Also resolved :)
