### ISSUE TITLE
Doesn't correctly resolve deps git/url in some circumstances

### ISSUE THREAD

**Issue by drewverlee** [juxt/pack.alpha#68]
Greetings!

*problem*

the resolved clj files that are stored in the docker image built by running `clj -A:pack mach.pack.alpha.jib --image-name example-juxt --image-type docker --base-image gcr.io/distroless/java:debug -m example.core` 

Aren't correct. Where they should contain integrant core, etc... instead what i see when i shell into the image is the ns for the project itself in the integrant directory:

```
/ # cat app/integrant__integrant__c673b85130e553feec6d4c5d2d1ec773a49c929c-..-..
-..-..-..-personal-example-project-to-show-juxt-pack-issue-src/example/core.clj 
(ns example.core)

(defn -main [] (println "helloword"))
```

Example[ repo](https://github.com/drewverlee/example_juxt_pack_issue) with same code.

Note this doesn't always happen, 

```
  org.clojure/data.csv {:git/url "https://github.com/clojure/data.csv.git"
                              :sha "e5beccad0bafdb8e78f19cba481d4ecef5fabf36"}
```

works correctly

**Comment by drewverlee** [comment]
My current hunch is that this is issue has something to do with the dep in question having a pom. Though i'm not sure what exactly, as a pom should be valid. I'm not very familiar with the specific of pom files.

**Comment by SevereOverfl0w** [comment]
I've tested your example with the clj tool, and it doesn't work there either:

```
/tmp/foo                                                                                                                                              8.82s 19:55:54
❯ cat deps.edn                
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: deps.edn
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {:deps
   2   │  {integrant {:git/url "https://github.com/alexanderkiel/integrant.git"
   3   │              :sha "c673b85130e553feec6d4c5d2d1ec773a49c929c"}}}
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

/tmp/foo                                                                                                                                              0.18s 19:56:36
❯ clj -Spath  
src:/home/dominic/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar:/home/dominic/.gitlibs/libs/integrant/integrant/c673b85130e553feec6d4c5d2d1ec773a49c929c/src:/home/dominic/.gitlibs/libs/integrant/integrant/c673b85130e553feec6d4c5d2d1ec773a49c929c/src/main/clojure:/home/dominic/.gitlibs/libs/integrant/integrant/c673b85130e553feec6d4c5d2d1ec773a49c929c/resources:/home/dominic/.m2/repository/org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.jar:/home/dominic/.m2/repository/org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.jar:/home/dominic/.m2/repository/weavejester/dependency/0.2.1/dependency-0.2.1.jar
```

Note that integrant/<sha>/src/main/clojure is on the classpath. I had a look at how tools.deps resolves paths for a pom:

https://github.com/clojure/tools.deps.alpha/blob/ca5ca61354f20fd4ffea6caac6162d1c2aaac08d/src/main/clojure/clojure/tools/deps/alpha/extensions/pom.clj#L101-L107

Looking at the provided pom.xml, I would expect this to work: https://github.com/alexanderkiel/integrant/blob/c673b85130e553feec6d4c5d2d1ec773a49c929c/pom.xml#L23 but I don't know anything about maven.

I think this needs to be raised upstream with tdeps, it's not a pack bug, but a tdeps one (if it is one, again, I don't know maven!).

**Comment by SevereOverfl0w** [comment]
Apologies. I missed that it is on the classpath there.

I'll look into this further. I'll keep notes here as I find things.

**Comment by SevereOverfl0w** [comment]
I tested with the lambda runner, and that also has this issue (presumably so do the others).  I assume this means that the problem is in the core.

I'm glad this is the case because the jib/docker stuff is a mystery to me!

**Comment by SevereOverfl0w** [comment]
Looks like this is an issue of tools.deps version. I'll bump the SHA in the README, which is using a new tools.deps.

You're running into https://clojure.atlassian.net/projects/TDEPS/issues/TDEPS-96

**Comment by SevereOverfl0w** [comment]
Try this sha for pack, it worked for me: c673b85130e553feec6d4c5d2d1ec773a49c929c
