### ISSUE TITLE
Jib: Add new option to pass extra arguments to `java` entrypoint command

### ISSUE THREAD

**Issue by dobladez** [juxt/pack.alpha#69]
For my current use-case, I need to pass extra param `--add-exports java.base/jdk.internal.misc=ALL-UNNAMED` to avoid a runtime error when using Edge+Yada on JDK 11.

I could have used environment variable `JDK_JAVA_OPTIONS` as a workaround, but that's impractical on my current setup. Also, I want the generated image to "just work" and not depend on such env variable.

**Comment by dobladez** [comment]
See PR #70

**Comment by SevereOverfl0w** [comment]
Fixed
