### ISSUE TITLE
Running auto add project does not provide required lib under java 11

### ISSUE THREAD

**Issue by mikepjb** [juxt/pack.alpha#75]
Hi Dominic,

Just been using pack to build & publish a jar, when using the auto-add feature - the alias created won't work right away because `javax.xml.bind/jaxb-api` is not provided

This is the alias I ended up using to successfully build:
```
{:extra-deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git"
                                                :sha "d9023b24c3d589ba6ebc66c5a25c0826ed28ead5"}
                               javax.xml.bind/jaxb-api {:mvn/version "2.4.0-b180830.0359"}}
                  :main-opts ["-m"]}
```

Should this be included?

**Comment by SevereOverfl0w** [comment]
This works on master. You're not using an up to date commit sha. I updated the sha in the juxt blog post you got this from :)
