### ISSUE TITLE
not packaging :local/root dep 

### ISSUE THREAD

**Issue by alidlo** [juxt/pack.alpha#82]
i have a nested repo defined via `:local/root` but it's classpaths are not being compiled, at least not when using skinny jar option

example setup: 

```
- lib 
   - src 
   - deps.edn
- deps.edn 
```
deps.edn 
```
{:deps {my-lib {:local/root "./lib"}}
```
lib/deps.edn
```
{:paths ["src"]
 :deps {}}
```

**Comment by SevereOverfl0w** [comment]
What arguments did you pass to the skinny main?  Generally, local/root deps work across pack.

**Comment by SevereOverfl0w** [comment]
I cannot reproduce:

```
❯ tree target 
target
├── app.jar
└── lib
    ├── my-lib__my-lib-src.jar
    ├── org.clojure__clojure__1.10.1.jar
    ├── org.clojure__core.specs.alpha__0.2.44.jar
    └── org.clojure__spec.alpha__0.2.176.jar
```

**my-lib__my-lib-src.jar** is the library "my-lib" you referred to.

**Comment by alidlo** [comment]
Ok, I'll try again just in case. When you tried, did you have a nested `.deps.edn`? 

These are the arguments: 
```
clojure -A:pack  mach.pack.alpha.skinny --no-libs --project-path my-lib.jar
```

**Comment by alidlo** [comment]
Yeah so I do see that trying it without the `--no-lib` option works. Sorry for not specifying that in original post, was following readme instructions for skinny jars as I'm posting to Clojars

**Comment by SevereOverfl0w** [comment]
Right, --no-libs ignores your libraries. If you're publishing to clojars, that's what you want.

Why do you want to include a library when you go to clojars?

**Comment by alidlo** [comment]
> If you're publishing to clojars, that's what you want.

Do you mean that's what you don't want? In that I should be adding the `no-libs` option? Since I don't want to include libraries when deploying to clojars.

To be clear, it works without the `no-libs` command, not with it. Your above command did not seem to have it, so it's likely where the discrepancy lies.

**Comment by SevereOverfl0w** [comment]
I'm a little confused, sorry. You should add --no-libs, yes. You shouldn't include your local/root dependency when going to clojars.

**Comment by alidlo** [comment]
ah, I figured since my setup worked as a git dependency (it has nested `:local/root` modules that are found with tools.deps) a similar setup could be achieved with pack.

would there be interest in supporting something to help this use-case? perhaps the classpaths for any local/root declarations can be found and packaged.. or there could be an easier way to build/deploy multiple modules inside a monorepo (in case seeing a use-case helps, here's the repo I'm packing for: https://github.com/alidlo/rewrap)

otherwise feel free to close this issue as it looks like it is not a bug, thanks

**Comment by SevereOverfl0w** [comment]
Why not release rewrap/main and rewrap/hiccup separately to clojars? That's why they're libs, rather than :paths

**Comment by alidlo** [comment]
yea I'd like to do that too, but was considering bundling them together too for convenience

**Comment by SevereOverfl0w** [comment]
That would cause potential conflicts for users if they got both on the classpath, I'd advise against that.

**Comment by alidlo** [comment]
ok got it, thanks for input, will go ahead and close issue
