### ISSUE TITLE
tools.deps api changes

### ISSUE THREAD

**Issue by puredanger** [juxt/pack.alpha#84]
Just wanted to drop a note that the newest version of tools.deps.alpha contains some api changes (moving towards getting out of alpha). So when you bump to tools.deps.alpha >= 0.9.745, you'll need to change the following things:

- load of `clojure.tools.deps.alpha.script.make-classpath` will fail as that has been removed (but you don't actually need to do this - loading `clojure.tools.deps.alpha` has been doing that automatically for a while now.
- `slurp-deps` => `clojure.tools.deps.alpha/slurp-deps`
- `merge-deps` => `clojure.tools.deps.alpha/merge-edns`
- `install-deps` => `clojure.tools.deps.alpha/root-deps`
- `slurp-deps` => `clojure.tools.deps.alpha/slurp-deps`

**Comment by awb99** [comment]
Would be great if this gets fixed. Will fail otherwise on current tools does alpha versions

**Comment by SevereOverfl0w** [comment]
Fixed by #94.
