### ISSUE TITLE
Proper usage with tools.deps 1.10.1.708

### ISSUE THREAD

**Issue by nivekuil** [juxt/pack.alpha#90]
I'm not sure if I'm doing something off-base or if the docs are out of date, but here is how I made an alias to build a docker image, if it helps anyone:
```
           :docker       {:replace-deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git"
                                                          :sha     "e518d9b2b70f4292c9988d2792b8667d88a6f4df"}}
                          :main-opts    ["-m" "mach.pack.alpha.jib"
                                         "-m" "app.ns"
                                         "--image-name" "my-image"]}}
```
Took me a while to figure out that you need to specify `-m` twice.

**Comment by SevereOverfl0w** [comment]
That doesn't seem right. That sounds like it's making a docker from pack itself.

**Comment by nivekuil** [comment]
Woops, that second "-m" should be the app ns. The difference from the docs I mean to point out is that you seem to need an `-m` for specifying the pack target too.

**Comment by SevereOverfl0w** [comment]
Ah, you've created a whole alias that does from start to finish.

The README assumes a generic alias which you would pass arguments to.

**Comment by nivekuil** [comment]
Yes, but I think the docs may still be mistaken in advertising this:
```
clj -A:pack mach.pack.alpha.jib -m app.ns --image-name my-app

WARNING: When invoking clojure.main, use -M
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
mach.pack.alpha.jib (No such file or directory)
```
You seem to need a `-m` before `mach.pack.alpha.jib`.

**Comment by SevereOverfl0w** [comment]
Does -M:pack work instead?

**Comment by nivekuil** [comment]
Without the `-m`? No:
```
clj -M:pack  mach.pack.alpha.jib -m app.ns --image-name my-app 
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
mach.pack.alpha.jib (No such file or directory)

Full report at:
/tmp/clojure-3189154151674651503.edn
```
